# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'fourthwindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtGui import QFont, QColor, QImage
from PyQt5.QtCore import  Qt
from matplotlib.pyplot import title
  


class Ui_fourthWindow(object):
    def load_ImageToListwidget(self, title, imgPath):
        icon = QtGui.QIcon(imgPath)
        item = QtWidgets.QListWidgetItem(icon,title)
        size = QtCore.QSize()
        size.setHeight(100)
        size.setWidth(400)
        item.setSizeHint(size)
        self.listWidget.setIconSize(size)
        self.listWidget.addItem(item)

    def setupUi(self, fourthWindow):
        fourthWindow.setObjectName("fourthWindow")
        fourthWindow.resize(640, 480)
        self.buttonBox = QtWidgets.QDialogButtonBox(fourthWindow)
        self.buttonBox.setGeometry(QtCore.QRect(10, 440, 621, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel)
        self.buttonBox.setObjectName("buttonBox")
        self.gridLayoutWidget = QtWidgets.QWidget(fourthWindow)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(200, 20, 431, 411))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.label_2 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 3, 1, 1)
        self.label = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.pushButton_3 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_3.setObjectName("pushButton_3")
        
        self.gridLayout.addWidget(self.pushButton_3, 2, 3, 1, 1)
        self.listWidget = QtWidgets.QListWidget(self.gridLayoutWidget)
        self.listWidget.setMouseTracking(True)
        self.listWidget.setSelectionMode(QtWidgets.QAbstractItemView.MultiSelection)
        self.load_ImageToListwidget('1',"E:\\Project Face regconition\\Face-Regconittion\\FacialRecognition\\extra_source\\User.0.1.jpg")
        self.load_ImageToListwidget('2',"E:\\Project Face regconition\\Face-Regconittion\\FacialRecognition\\extra_source\\User.0.12.jpg")
        self.listWidget.setObjectName("listWidget")

        self.gridLayout.addWidget(self.listWidget, 1, 0, 1, 4)
        self.pushButton_4 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_4.setObjectName("pushButton_4")
        self.gridLayout.addWidget(self.pushButton_4, 2, 2, 1, 1)
        self.pushButton = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton.setObjectName("pushButton")
        self.gridLayout.addWidget(self.pushButton, 2, 0, 1, 1)
        self.pushButton_2 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_2.setObjectName("pushButton_2")
        self.gridLayout.addWidget(self.pushButton_2, 2, 1, 1, 1)
        self.verticalLayoutWidget = QtWidgets.QWidget(fourthWindow)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(20, 40, 160, 161))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.textBrowser = QtWidgets.QTextBrowser(self.verticalLayoutWidget)
        self.textBrowser.setObjectName("textBrowser")
        self.verticalLayout.addWidget(self.textBrowser)
        self.label_4 = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.verticalLayout.addWidget(self.label_4)
        self.spinBox = QtWidgets.QSpinBox(self.verticalLayoutWidget)
        self.spinBox.setObjectName("spinBox")
        self.verticalLayout.addWidget(self.spinBox)
        self.label_3 = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3)
        self.lineEdit = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.lineEdit.setObjectName("lineEdit")
        self.verticalLayout.addWidget(self.lineEdit)
        self.label_5 = QtWidgets.QLabel(fourthWindow)
        self.label_5.setGeometry(QtCore.QRect(20, 350, 141, 121))
        self.label_5.setWordWrap(True)
        self.label_5.setObjectName("label_5")

        self.retranslateUi(fourthWindow)
        self.buttonBox.accepted.connect(fourthWindow.accept)
        self.buttonBox.rejected.connect(fourthWindow.reject)
        QtCore.QMetaObject.connectSlotsByName(fourthWindow)

    def retranslateUi(self, fourthWindow):
        _translate = QtCore.QCoreApplication.translate
        fourthWindow.setWindowTitle(_translate("fourthWindow", "Dialog"))
        self.label_2.setText(_translate("fourthWindow", "Selected:"))
        self.label.setText(_translate("fourthWindow", "List of selected image"))
        self.pushButton_3.setText(_translate("fourthWindow", "Train"))
        self.pushButton_4.setText(_translate("fourthWindow", "Remove Image"))
        self.pushButton.setText(_translate("fourthWindow", "Browser Image"))
        self.pushButton_2.setText(_translate("fourthWindow", "Select all"))
        self.textBrowser.setHtml(_translate("fourthWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt; font-weight:600; color:#ff0000;\">USER INFO</span></p></body></html>"))
        self.label_4.setText(_translate("fourthWindow", "User Id:"))
        self.label_3.setText(_translate("fourthWindow", "User Name:"))
        self.label_5.setText(_translate("fourthWindow", "Note: User must select images before pushing \"Remove Image\" or \"Train\" buttons after adding them into the showing list to confirm."))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    fourthWindow = QtWidgets.QDialog()
    ui = Ui_fourthWindow()
    ui.setupUi(fourthWindow)
    fourthWindow.show()
    sys.exit(app.exec_())
